### ISSUE TITLE
Enable Password Visibility During Registration and Authentication

### ISSUE THREAD

**Issue by Natali-Kotelnitska** [ita-social-projects/ZeroWaste#609]
**As a** user **I want to** have the possibility to see my password when I authenticate **so that** I can avoid typing errors. 

**Description**
1. Add a new feature in the login page that allows the user to toggle the visibility of their password.
2. Show an icon of an eye next to the password field that changes to an eye with a slash when the user clicks on it.
3. When the user clicks on the icon, the password field should switch from type="password" to type="text" and vice versa.
4. The default state of the password field should be hidden.

### Acceptance Criteria
The user can see their password when they click on the eye icon.
The user can hide their password when they click on the eye icon again.
The password field is hidden by default.

### Tasks 

- [x] 1. Add an eye icon next to the password field in the login page.

- [x] 2. Add a click event handler to the eye icon that toggles the type of the password field.

- [x] 3. Add a style class to the eye icon that changes its appearance when the password field is visible or hidden.

- [x] 4. Convert slim files into erb files for Registration, Authorization, and User account.
